### ISSUE TITLE
Trying to launch the TypeScript file results in a huge error strack trace

### ISSUE THREAD

**Issue by talentlessguy** [antfu/esno#2]
my ts code, also available in [this repo](https://github.com/talentlessguy/tinyhttp/blob/master/site/server.ts):

```ts
import { App } from '@tinyhttp/app'
import serve from 'sirv'
import { markdownStaticHandler as md } from '@tinyhttp/markdown'
import { logger } from '../packages/logger/src'
import { createReadStream } from 'fs'
import { transformMWPageStream, transformPageIndexStream } from './streams'
import fetchCache from 'node-fetch-cache'
import hljs from 'highlight.js'

const fetch = fetchCache(`${__dirname}/.cache`)

const app = new App({
  settings: {
    networkExtensions: true
  }
})

app
  .use(
    logger({
      ip: true,
      timestamp: true,
      output: {
        callback: console.log,
        color: false
      }
    })
  )
  .use(
    serve('static', {
      dev: process.env.NODE_ENV !== 'production',
      immutable: process.env.NODE_ENV === 'production'
    })
  )

app.listen(3000, () => console.log(`Running on http://localhost:3000`))
```

the command I run:

```sh
$ esno server.ts
```

the output I get:

```
➜ pnpx esno server.ts 
/home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/esbuild@0.7.22/node_modules/esbuild/bin/esbuild:2
throw new Error(`esbuild: Failed to install correctly
^

Error: esbuild: Failed to install correctly

Make sure you don't have "ignore-scripts" set to true. You can check this with
"npm config get ignore-scripts". If that returns true you can reset it back to
false using "npm config set ignore-scripts false" and then reinstall esbuild.

    at Object.<anonymous> (/home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/esbuild@0.7.22/node_modules/esbuild/bin/esbuild:2:7)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
/home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/esbuild@0.7.22/node_modules/esbuild/lib/main.js:1
Error: Command failed: /home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/esbuild@0.7.22/node_modules/esbuild/bin/esbuild --service=0.7.22
/home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/esbuild@0.7.22/node_modules/esbuild/bin/esbuild:2
throw new Error(`esbuild: Failed to install correctly
^

Error: esbuild: Failed to install correctly

Make sure you don't have "ignore-scripts" set to true. You can check this with
"npm config get ignore-scripts". If that returns true you can reset it back to
false using "npm config set ignore-scripts false" and then reinstall esbuild.

    at Object.<anonymous> (/home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/esbuild@0.7.22/node_modules/esbuild/bin/esbuild:2:7)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47

    at checkExecSyncError (node:child_process:636:11)
    at Object.execFileSync (node:child_process:654:15)
    at runServiceSync (/home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/esbuild@0.7.22/node_modules/esbuild/lib/main.js:802:30)
    at Object.transformSync (/home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/esbuild@0.7.22/node_modules/esbuild/lib/main.js:711:3)
    at compile (/home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/esbuild-register@1.1.0_esbuild@0.7.22/node_modules/esbuild-register/dist/node.js:63:51)
    at Object._compile (/home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/pirates@4.0.1/node_modules/pirates/lib/index.js:93:29)
    at Module._extensions..js (node:internal/modules/cjs/loader:1131:10) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(979) [Uint8Array] [
       47, 104, 111, 109, 101,  47, 118,  49, 114, 116, 108,  47,
       67, 111, 100, 105, 110, 103,  47, 116, 105, 110, 121, 104,
      116, 116, 112,  47, 110, 111, 100, 101,  95, 109, 111, 100,
      117, 108, 101, 115,  47,  46, 112, 110, 112, 109,  47, 101,
      115,  98, 117, 105, 108, 100,  64,  48,  46,  55,  46,  50,
       50,  47, 110, 111, 100, 101,  95, 109, 111, 100, 117, 108,
      101, 115,  47, 101, 115,  98, 117, 105, 108, 100,  47,  98,
      105, 110,  47, 101, 115,  98, 117, 105, 108, 100,  58,  50,
       10, 116, 104, 114,
      ... 879 more items
    ]
  ],
  pid: 47120,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(979) [Uint8Array] [
     47, 104, 111, 109, 101,  47, 118,  49, 114, 116, 108,  47,
     67, 111, 100, 105, 110, 103,  47, 116, 105, 110, 121, 104,
    116, 116, 112,  47, 110, 111, 100, 101,  95, 109, 111, 100,
    117, 108, 101, 115,  47,  46, 112, 110, 112, 109,  47, 101,
    115,  98, 117, 105, 108, 100,  64,  48,  46,  55,  46,  50,
     50,  47, 110, 111, 100, 101,  95, 109, 111, 100, 117, 108,
    101, 115,  47, 101, 115,  98, 117, 105, 108, 100,  47,  98,
    105, 110,  47, 101, 115,  98, 117, 105, 108, 100,  58,  50,
     10, 116, 104, 114,
    ... 879 more items
  ]
}
node:child_process:675
    throw err;
    ^

Error: Command failed: node -r /home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/esm@3.2.25/node_modules/esm/esm.js -r /home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/esbuild-register@1.1.0_esbuild@0.7.22/node_modules/esbuild-register/register.js "server.ts"
    at checkExecSyncError (node:child_process:636:11)
    at execSync (node:child_process:672:15)
    at Object.<anonymous> (/home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/esno@0.2.4/node_modules/esno/esno.js:13:1)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 47113,
  stdout: null,
  stderr: null
}
```

**system info**

- node version: 15.2.1
- esno version: 0.2.4
- esbuild version: 0.7.22

**Comment by antfu** [comment]
Can you try esno v0.3.0 to see if this still presents?

**Comment by talentlessguy** [comment]
@antfu still getting this error on 0.3.0:

```
/home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/esbuild@0.8.17/node_modules/esbuild/bin/esbuild:2
throw new Error(`esbuild: Failed to install correctly
^

Error: esbuild: Failed to install correctly

Make sure you don't have "ignore-scripts" set to true. You can check this with
"npm config get ignore-scripts". If that returns true you can reset it back to
false using "npm config set ignore-scripts false" and then reinstall esbuild.

    at Object.<anonymous> (/home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/esbuild@0.8.17/node_modules/esbuild/bin/esbuild:2:7)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
/home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/esbuild@0.8.17/node_modules/esbuild/lib/main.js:1
Error: Command failed: /home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/esbuild@0.8.17/node_modules/esbuild/bin/esbuild --service=0.8.17
/home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/esbuild@0.8.17/node_modules/esbuild/bin/esbuild:2
throw new Error(`esbuild: Failed to install correctly
^

Error: esbuild: Failed to install correctly

Make sure you don't have "ignore-scripts" set to true. You can check this with
"npm config get ignore-scripts". If that returns true you can reset it back to
false using "npm config set ignore-scripts false" and then reinstall esbuild.

    at Object.<anonymous> (/home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/esbuild@0.8.17/node_modules/esbuild/bin/esbuild:2:7)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47

    at checkExecSyncError (node:child_process:636:11)
    at Proxy.execFileSync (node:child_process:654:15)
    at runServiceSync (/home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/esbuild@0.8.17/node_modules/esbuild/lib/main.js:1131:30)
    at Object.transformSync (/home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/esbuild@0.8.17/node_modules/esbuild/lib/main.js:1033:3)
    at compile (/home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/esbuild-register@1.1.1_esbuild@0.8.17/node_modules/esbuild-register/dist/node.js:63:62)
    at Object._compile (/home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/pirates@4.0.1/node_modules/pirates/lib/index.js:93:29)
    at Module._extensions..js (node:internal/modules/cjs/loader:1131:10) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(979) [Uint8Array] [
       47, 104, 111, 109, 101,  47, 118,  49, 114, 116, 108,  47,
       67, 111, 100, 105, 110, 103,  47, 116, 105, 110, 121, 104,
      116, 116, 112,  47, 110, 111, 100, 101,  95, 109, 111, 100,
      117, 108, 101, 115,  47,  46, 112, 110, 112, 109,  47, 101,
      115,  98, 117, 105, 108, 100,  64,  48,  46,  56,  46,  49,
       55,  47, 110, 111, 100, 101,  95, 109, 111, 100, 117, 108,
      101, 115,  47, 101, 115,  98, 117, 105, 108, 100,  47,  98,
      105, 110,  47, 101, 115,  98, 117, 105, 108, 100,  58,  50,
       10, 116, 104, 114,
      ... 879 more items
    ]
  ],
  pid: 376243,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(979) [Uint8Array] [
     47, 104, 111, 109, 101,  47, 118,  49, 114, 116, 108,  47,
     67, 111, 100, 105, 110, 103,  47, 116, 105, 110, 121, 104,
    116, 116, 112,  47, 110, 111, 100, 101,  95, 109, 111, 100,
    117, 108, 101, 115,  47,  46, 112, 110, 112, 109,  47, 101,
    115,  98, 117, 105, 108, 100,  64,  48,  46,  56,  46,  49,
     55,  47, 110, 111, 100, 101,  95, 109, 111, 100, 117, 108,
    101, 115,  47, 101, 115,  98, 117, 105, 108, 100,  47,  98,
    105, 110,  47, 101, 115,  98, 117, 105, 108, 100,  58,  50,
     10, 116, 104, 114,
    ... 879 more items
  ]
}
node:child_process:675
    throw err;
    ^

Error: Command failed: node -r /home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/esm@3.2.25/node_modules/esm/esm.js -r /home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/esbuild-register@1.1.1_esbuild@0.8.17/node_modules/esbuild-register/register.js "server.ts"
    at checkExecSyncError (node:child_process:636:11)
    at execSync (node:child_process:672:15)
    at Object.<anonymous> (/home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/esno@0.3.0/node_modules/esno/esno.js:13:1)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 376235,
  stdout: null,
  stderr: null
}
```

**Comment by antfu** [comment]
Seems to work fine for me. Can you share a repro? Thanks

**Comment by talentlessguy** [comment]
@antfu I linked the reproduction repository in the original issue but here it is: https://github.com/talentlessguy/tinyhttp

after cloning, run `pnpm install && pnpm build -r`, then go to `site` folder and run `pnpm i -D esno` there, then try to do `pnpx esno server.ts`

**Comment by talentlessguy** [comment]
Update: now it throws this error:

```
➜ pnpx esno server.ts
/home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/esbuild@0.8.22/node_modules/esbuild/bin/esbuild:2
throw new Error(`esbuild: Failed to install correctly
^

Error: esbuild: Failed to install correctly

Make sure you don't have "ignore-scripts" set to true. You can check this with
"npm config get ignore-scripts". If that returns true you can reset it back to
false using "npm config set ignore-scripts false" and then reinstall esbuild.
```

`ignore-scripts` isn't set to `true`, so the error message is wrong:

```
➜ pnpm config get ignore-scripts
false
```

looks like it isn't the `esno` but `esbuild` issue, interesting...

**Comment by talentlessguy** [comment]
The error doesn't happen with `esbuild-linux-64`:

```
➜ ./node_modules/esbuild-linux-64/bin/esbuild --version
0.8.22
```

**Comment by talentlessguy** [comment]
@antfu oh, with new version it works! thank you for fixing this

**Comment by talentlessguy** [comment]
Although it still happens when having it installed as a dev dep in a pnpm monorepo

but globally it works
